# Generated by Django 6.0.2 on 2026-02-18 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='member_photos/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('id_card', models.FileField(upload_to='id_cards/')),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('VL', 'volunteer'), ('CL', 'community leader'), ('M', 'member'), ('T', 'trainee')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
