# Generated by Django 6.0.2 on 2026-02-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='gdanworldwide123@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(),
        ),
    ]
