# Generated by Django 6.0.2 on 2026-03-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_member_email_alter_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Community Leader', 'Community Leader'), ('Donor', 'Donor'), ('Trainee', 'Trainee')], max_length=20),
        ),
    ]
